@orcamento_pessoal_api_HostAddress = http://localhost:5097

### Get Weather Forecast
GET {{orcamento_pessoal_api_HostAddress}}/weatherforecast/
Accept: application/json

### Authenticate User
POST {{orcamento_pessoal_api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "sandro",
  "password": "123456"
}

### Logout User
POST {{orcamento_pessoal_api_HostAddress}}/api/auth/logout
Accept: application/json

### Get Transactions
GET {{orcamento_pessoal_api_HostAddress}}/api/transaction/getAll

### Get salt
GET {{orcamento_pessoal_api_HostAddress}}/api/transaction/salt

### Get hash
GET {{orcamento_pessoal_api_HostAddress}}/api/transaction/hash

### Create User
POST {{orcamento_pessoal_api_HostAddress}}/api/Users/create
Accept: application/json

{
  "name": "Pedro Celestino",
  "login": "pedrao",
  "password": "123456"
}